# keywords = {
#     'set3': ['trying to keep my balance in my dehydrated state',
#              'no one in sight, not a building, car, or structure of any kind',
#              'flat road was replaced by short rolling hills',
#              'hitting my water bottles pretty regularly',
#              'somewhere in the neighborhood of two hundred degrees',
#              'sun was beginning to beat down',
#              'drop from heatstroke on a gorgeous day',
#              'water bottles contained only a few tantalizing sips',
#              'high deserts of California',
#              'enjoyed the serenity of an early-summer evening',
#              'traveling through the high deserts of California in June',
#              'ROUGH ROAD AHEAD: DO NOT EXCEED POSTED SPEED LIMIT',
#              'long, crippling hill',
#              'tarlike substance followed by brackish water',
#              'thriving little spot at one time',
#              'fit the traditional definition of a ghost town',
#              'Wide rings of dried sweat circled my shirt',
#              'growing realization that I could drop from heatstroke on a gorgous day in June',
#              'water bottle contained only a few tantalizing sips',
#              'wide rings of dried sweat circled my shirt',
#              'checked my water supply',
#              'brackish water faling somewhere in the neighborhood of two hundred degrees',
#              'birds would pick me clean'],
#     'set4': ['will take that test again', 'many of the things that she had thought of as strange', 'not like the kind we had before', 'I failed the test', 'rich sweet scent', 'when the snow melts', 'geese return', 'hibiscus is budding', 'gentle grandmother', 'distinctive V was etched against the evening sky', 'familiar fragrance filled her lungs', 'could almost feel light strands of her grandmother long gray hair', 'attitude towards her new country and her driving test', 'hibiscus plant in the winter is not as beautiful in the bitter cold', 'adapts and survives', 'returns to its beautiful state in the spring', 'bitter about her new country and driving test', 'new start or new opportunity', 'memories of home', 'overcoming her obstacles', 'noticed tear stains on her a daughter cheeks and her puffy eyes', 'symbolize change and adoption', 'make it through the winter into the spring', 'life is blooming', 'she was still too shaky to say the words at home', 'bitter melon'],
#     'set5': ['always be grateful to my parents for their love and sacrifice', 'rich culinary skills', 'love of cooking', 'passionate Cuban music', 'aromas of the kitchen', 'innocence of childhood', 'congregation of family and friends', 'endless celebrations', 'warm home', 'came together in great solidarity and friendship', 'close-knit community of honest, hardworking immigrants', 'kept their arms and door open to the many people we considered family', 'came selflessly', 'struggled both personally and financially', 'facing cultural hardships', 'overt racism was the norm', 'drove them to endure these hard times', 'strength and perseverance', 'love and sacrifice', 'spirit of generosity impressed upon me at such an early age', 'demonstration of how important family and friends are', 'teachings have been basis of my life', 'warmth of the kitchen', 'humble house', 'not just scent and music but life and love', 'definition of family', 'rich culinary skills', 'never forget how my parents turned this simple house into a home'],
#     'set6': ['one of safety', 'dirigibles from outside of the United States used hydrogen instead of helium', 'nature itself', 'winds on top of the building were constantly shifting', 'violent air currents', 'law against airships flying too low over urban areas', 'moored in open landing fields', 'could be weighted down in the back with lead weights', 'dangling high above pedestrians on the street was neither practical nor safe', 'swivel around and around the mooring mast', 'how much worse that accident could have been', 'could not simply drop a mooring mast on top of the empire state building flat roof', 'stress of the dirigible load', 'mooring air ships to a fixed mast', 'puncture the dirigible shell', 'neither practical nor safe']
# }

keywords = {
    'set3': ['trying to keep my balance in my dehydrated state',
             'no one in sight, not a building, car, or structure of any kind',
             'flat road was replaced by short rolling hills',
             'hitting my water bottles pretty regularly',
             'somewhere in the neighborhood of two hundred degrees',
             'sun was beginning to beat down',
             'drop from heatstroke on a gorgeous day',
             'water bottles contained only a few tantalizing sips',
             'high deserts of California',
             'enjoyed the serenity of an early-summer evening',
             'traveling through the high deserts of California in June',
             'ROUGH ROAD AHEAD: DO NOT EXCEED POSTED SPEED LIMIT',
             'long, crippling hill',
             'tarlike substance followed by brackish water',
             'thriving little spot at one time',
             'fit the traditional definition of a ghost town',
             'Wide rings of dried sweat circled my shirt',
             'growing realization that I could drop from heatstroke on a gorgous day in June',
             'water bottle contained only a few tantalizing sips',
             'wide rings of dried sweat circled my shirt',
             'checked my water supply',
             'brackish water faling somewhere in the neighborhood of two hundred degrees',
             'birds would pick me clean'],
    'set4': ['will take that test again', 'many of the things that she had thought of as strange', 'not like the kind we had before', 'I failed the test', 'rich sweet scent', 'when the snow melts', 'geese return', 'hibiscus is budding', 'gentle grandmother', 'distinctive V was etched against the evening sky', 'familiar fragrance filled her lungs', 'could almost feel light strands of her grandmother long gray hair', 'attitude towards her new country and her driving test', 'hibiscus plant in the winter is not as beautiful in the bitter cold', 'adapts and survives', 'returns to its beautiful state in the spring', 'bitter about her new country and driving test', 'new start or new opportunity', 'memories of home', 'overcoming her obstacles', 'noticed tear stains on her a daughter cheeks and her puffy eyes', 'symbolize change and adoption', 'make it through the winter into the spring', 'life is blooming', 'she was still too shaky to say the words at home', 'bitter melon'],
    'set5': ['always be grateful to my parents for their love and sacrifice', 'rich culinary skills', 'love of cooking', 'passionate Cuban music', 'aromas of the kitchen', 'innocence of childhood', 'congregation of family and friends', 'endless celebrations', 'warm home', 'came together in great solidarity and friendship', 'close-knit community of honest, hardworking immigrants', 'kept their arms and door open to the many people we considered family', 'came selflessly', 'struggled both personally and financially', 'facing cultural hardships', 'overt racism was the norm', 'drove them to endure these hard times', 'strength and perseverance', 'love and sacrifice', 'spirit of generosity', 'impressed upon me at such an early age', 'demonstration of how important family and friends are', 'teachings have been basis of my life', 'warmth of the kitchen', 'humble house', 'not just scent and music but life and love', 'definition of family', 'rich culinary skills', 'never forget how my parents', 'turned this simple house into a home', 'blond brick', 'surrogate grandparents', 'whatever work they could find'],
    'set6': ['one of safety', 'dirigibles from outside of the United States used hydrogen instead of helium', 'nature itself', 'winds on top of the building were constantly shifting', 'violent air currents', 'law against airships flying too low over urban areas', 'moored in open landing fields', 'could be weighted down in the back with lead weights', 'dangling high above pedestrians on the street was neither practical nor safe', 'swivel around and around the mooring mast', 'how much worse that accident could have been', 'could not simply drop a mooring mast on top of the empire state building flat roof', 'stress of the dirigible load', 'mooring air ships to a fixed mast', 'puncture the dirigible shell', 'neither practical nor safe']
}

def get_keywords(set_name):
    return keywords[set_name]
